import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "../context/AuthCotext";
import { TabProvider } from "../context/tabContext";
import BottomNav from "./components/BottomNav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <TabProvider>
      <body>
        {children}
      <BottomNav />
      </body>
        </TabProvider>
      </AuthProvider>
    </html>
  );
}
